//! Cosmos ecosystem chain metadata definitions

use crate::registry::{
    AddressMetadata, ChainMetadata, CharSet, ChecksumType, EncodingType, Network,
    PublicKeyMetadata, PublicKeyType,
};
use crate::Chain;

/// Get all Cosmos ecosystem chain metadata
pub fn cosmos_metadata() -> Vec<ChainMetadata> {
    vec![
        ChainMetadata {
            id: Chain::CosmosHub,
            name: "Cosmos Hub".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Bech32,
                char_set: Some(CharSet::Base32),
                exact_length: None,
                length_range: Some((14, 74)),
                prefixes: vec![],
                hrps: vec!["cosmos".to_string()],
                version_bytes: vec![],
                checksum: Some(ChecksumType::Bech32),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(64), // 32 bytes = 64 hex chars
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Ed25519,
                checksum: None,
            }],
        },
        ChainMetadata {
            id: Chain::Osmosis,
            name: "Osmosis".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Bech32,
                char_set: Some(CharSet::Base32),
                exact_length: None,
                length_range: Some((14, 74)),
                prefixes: vec![],
                hrps: vec!["osmo".to_string()],
                version_bytes: vec![],
                checksum: Some(ChecksumType::Bech32),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(64),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Ed25519,
                checksum: None,
            }],
        },
        ChainMetadata {
            id: Chain::Juno,
            name: "Juno".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Bech32,
                char_set: Some(CharSet::Base32),
                exact_length: None,
                length_range: Some((14, 74)),
                prefixes: vec![],
                hrps: vec!["juno".to_string()],
                version_bytes: vec![],
                checksum: Some(ChecksumType::Bech32),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(64),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Ed25519,
                checksum: None,
            }],
        },
        ChainMetadata {
            id: Chain::Akash,
            name: "Akash".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Bech32,
                char_set: Some(CharSet::Base32),
                exact_length: None,
                length_range: Some((14, 74)),
                prefixes: vec![],
                hrps: vec!["akash".to_string()],
                version_bytes: vec![],
                checksum: Some(ChecksumType::Bech32),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(64),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Ed25519,
                checksum: None,
            }],
        },
        ChainMetadata {
            id: Chain::Stargaze,
            name: "Stargaze".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Bech32,
                char_set: Some(CharSet::Base32),
                exact_length: None,
                length_range: Some((14, 74)),
                prefixes: vec![],
                hrps: vec!["stars".to_string()],
                version_bytes: vec![],
                checksum: Some(ChecksumType::Bech32),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(64),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Ed25519,
                checksum: None,
            }],
        },
        ChainMetadata {
            id: Chain::SecretNetwork,
            name: "Secret Network".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Bech32,
                char_set: Some(CharSet::Base32),
                exact_length: None,
                length_range: Some((14, 74)),
                prefixes: vec![],
                hrps: vec!["secret".to_string()],
                version_bytes: vec![],
                checksum: Some(ChecksumType::Bech32),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(64),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Ed25519,
                checksum: None,
            }],
        },
        ChainMetadata {
            id: Chain::Terra,
            name: "Terra".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Bech32,
                char_set: Some(CharSet::Base32),
                exact_length: None,
                length_range: Some((14, 74)),
                prefixes: vec![],
                hrps: vec!["terra".to_string()],
                version_bytes: vec![],
                checksum: Some(ChecksumType::Bech32),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(64),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Ed25519,
                checksum: None,
            }],
        },
        ChainMetadata {
            id: Chain::Kava,
            name: "Kava".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Bech32,
                char_set: Some(CharSet::Base32),
                exact_length: None,
                length_range: Some((14, 74)),
                prefixes: vec![],
                hrps: vec!["kava".to_string()],
                version_bytes: vec![],
                checksum: Some(ChecksumType::Bech32),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(64),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Ed25519,
                checksum: None,
            }],
        },
        ChainMetadata {
            id: Chain::Regen,
            name: "Regen".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Bech32,
                char_set: Some(CharSet::Base32),
                exact_length: None,
                length_range: Some((14, 74)),
                prefixes: vec![],
                hrps: vec!["regen".to_string()],
                version_bytes: vec![],
                checksum: Some(ChecksumType::Bech32),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(64),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Ed25519,
                checksum: None,
            }],
        },
        ChainMetadata {
            id: Chain::Sentinel,
            name: "Sentinel".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Bech32,
                char_set: Some(CharSet::Base32),
                exact_length: None,
                length_range: Some((14, 74)),
                prefixes: vec![],
                hrps: vec!["sent".to_string()],
                version_bytes: vec![],
                checksum: Some(ChecksumType::Bech32),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(64),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Ed25519,
                checksum: None,
            }],
        },
    ]
}
