//! EVM chain metadata definitions
//!
//! This module defines metadata for all EVM-compatible chains.

use crate::registry::{
    AddressMetadata, ChainMetadata, CharSet, ChecksumType, EncodingType, Network,
    PublicKeyMetadata, PublicKeyType,
};
use crate::Chain;

/// Get all EVM chain metadata
pub fn evm_metadata() -> Vec<ChainMetadata> {
    vec![
        ChainMetadata {
            id: Chain::Ethereum,
            name: "Ethereum".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(42),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                version_bytes: vec![],
                checksum: Some(ChecksumType::EIP55),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: None,
                length_range: Some((66, 130)), // 33 or 65 bytes (compressed or uncompressed)
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Secp256k1,
                checksum: None,
            }],
        },
        ChainMetadata {
            id: Chain::Polygon,
            name: "Polygon".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(42),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                version_bytes: vec![],
                checksum: Some(ChecksumType::EIP55),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: None,
                length_range: Some((66, 130)),
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Secp256k1,
                checksum: None,
            }],
        },
        ChainMetadata {
            id: Chain::BSC,
            name: "Binance Smart Chain".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(42),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                version_bytes: vec![],
                checksum: Some(ChecksumType::EIP55),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: None,
                length_range: Some((66, 130)),
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Secp256k1,
                checksum: None,
            }],
        },
        ChainMetadata {
            id: Chain::Avalanche,
            name: "Avalanche".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(42),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                version_bytes: vec![],
                checksum: Some(ChecksumType::EIP55),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: None,
                length_range: Some((66, 130)),
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Secp256k1,
                checksum: None,
            }],
        },
        ChainMetadata {
            id: Chain::Arbitrum,
            name: "Arbitrum".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(42),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                version_bytes: vec![],
                checksum: Some(ChecksumType::EIP55),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: None,
                length_range: Some((66, 130)),
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Secp256k1,
                checksum: None,
            }],
        },
        ChainMetadata {
            id: Chain::Optimism,
            name: "Optimism".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(42),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                version_bytes: vec![],
                checksum: Some(ChecksumType::EIP55),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: None,
                length_range: Some((66, 130)),
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Secp256k1,
                checksum: None,
            }],
        },
        ChainMetadata {
            id: Chain::Base,
            name: "Base".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(42),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                version_bytes: vec![],
                checksum: Some(ChecksumType::EIP55),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: None,
                length_range: Some((66, 130)),
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Secp256k1,
                checksum: None,
            }],
        },
        ChainMetadata {
            id: Chain::Fantom,
            name: "Fantom".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(42),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                version_bytes: vec![],
                checksum: Some(ChecksumType::EIP55),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: None,
                length_range: Some((66, 130)),
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Secp256k1,
                checksum: None,
            }],
        },
        ChainMetadata {
            id: Chain::Celo,
            name: "Celo".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(42),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                version_bytes: vec![],
                checksum: Some(ChecksumType::EIP55),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: None,
                length_range: Some((66, 130)),
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Secp256k1,
                checksum: None,
            }],
        },
        ChainMetadata {
            id: Chain::Gnosis,
            name: "Gnosis".to_string(),
            address_formats: vec![AddressMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: Some(42),
                length_range: None,
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                version_bytes: vec![],
                checksum: Some(ChecksumType::EIP55),
                network: Some(Network::Mainnet),
            }],
            public_key_formats: vec![PublicKeyMetadata {
                encoding: EncodingType::Hex,
                char_set: Some(CharSet::Hex),
                exact_length: None,
                length_range: Some((66, 130)),
                prefixes: vec!["0x".to_string()],
                hrps: vec![],
                key_type: PublicKeyType::Secp256k1,
                checksum: None,
            }],
        },
    ]
}
